In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.mat([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
a = np.array([[1,2,3],[4,5,6]])

b = np.array([[1,2,3],[3,4,5],[5,6,7]])

print(a @ b)

[[22 28 34]
 [49 64 79]]


In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.mat(a)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
a = np.mat([[1,2,3],[4,5,6]])

b = np.mat([[1,2,3],[3,4,5],[5,6,7]])

print(a*b)

[[22 28 34]
 [49 64 79]]


In [7]:
a * a.I

matrix([[ 1.00000000e+00,  3.60822483e-16],
        [-1.11022302e-15,  1.00000000e+00]])

In [8]:
a.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [9]:
inputs = np.mat([5, 10, 15])
weights = np.mat([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])
result = inputs * weights
result

matrix([[2.5, 6.5, 0.5]])

In [10]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import scale
boston = load_boston()
X, y = scale(boston.data), boston.target

In [11]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

regression.fit(X, y)

LinearRegression()

In [12]:
print('R2 %0.3f' % regression.score(X, y))

R2 0.741


In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder()

qualitative = ['red', 'red', 'green', 'blue',
               'red', 'blue', 'blue', 'green']

labels = lbl.fit_transform(qualitative).reshape(8,1)

print(enc.fit_transform(labels).toarray())

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [14]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

pf = PolynomialFeatures(degree=2)
poly_X = pf.fit_transform(X)

X_train, X_test, y_train, y_test = (
   train_test_split(poly_X, y, test_size=0.33, random_state=42))

from sklearn.linear_model import Ridge

reg_regression = Ridge(alpha=0.1, normalize=True)

reg_regression.fit(X_train,y_train)

print ('R2: %0.3f' % r2_score(y_test,reg_regression.predict(X_test)))

R2: 0.820


In [15]:
import numpy as np

a = np.array([0, 0, 0, 0, 1, 1, 1, 1])

b = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(8,1)

from sklearn.linear_model import LinearRegression

regression = LinearRegression()

regression.fit(b,a)

print (regression.predict(b)>0.5)

[False False False False  True  True  True  True]


In [16]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

binary_y = np.array(y >= 40).astype(int)

X_train, X_test, y_train, y_test = train_test_split(X,
    binary_y, test_size=0.33, random_state=5)

logistic = LogisticRegression()

logistic.fit(X_train,y_train)

from sklearn.metrics import accuracy_score

print('In-sample accuracy: %0.3f' % accuracy_score(y_train, logistic.predict(X_train)))

print('Out-of-sample accuracy: %0.3f' % accuracy_score(y_test, logistic.predict(X_test)))

In-sample accuracy: 0.979
Out-of-sample accuracy: 0.958


In [17]:
for var,coef in zip(boston.feature_names, logistic.coef_[0]):
    print ("%7s : %7.3f" % (var, coef))

   CRIM :   0.086
     ZN :   0.230
  INDUS :   0.580
   CHAS :  -0.029
    NOX :  -0.304
     RM :   1.769
    AGE :  -0.127
    DIS :  -0.539
    RAD :   0.919
    TAX :  -0.165
PTRATIO :  -0.782
      B :   0.077
  LSTAT :  -1.628


In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

pf = PolynomialFeatures(degree=2)
poly_X = pf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(poly_X, y, test_size=0.33, random_state=42)

from sklearn.linear_model import Ridge

reg_regression = Ridge(alpha=0.1, normalize=True)
reg_regression.fit(X_train,y_train)

print ('R2: %0.3f' % r2_score(y_test,reg_regression.predict(X_test)))

R2: 0.820


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

SGD = SGDRegressor(penalty=None,
                   learning_rate='invscaling',
                   eta0=0.01, power_t=0.25,
                   max_iter=5, tol=None)

power = 17
check = [2**i for i in range(power+1)]

for i in range(400):
    for j in range(X_train.shape[0]):
        SGD.partial_fit(X_train[j,:].reshape(1,13),
                        y_train[j].reshape(1,))
        count = (j+1) + X_train.shape[0] * i
        
        if count in check:
            R2 = r2_score(y_test,SGD.predict(X_test))
            print ('Example %6i R2 %0.3f coef: %s' %

            (count, R2, ' '.join(map(
              lambda x:'%0.3f' %x, SGD.coef_))))