In [2]:
import numpy as np

In [3]:
np.ones((10,5)).shape

(10, 5)

In [4]:
np.ones((3,4,5), dtype=np.float64).strides

(160, 40, 8)

In [5]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [6]:
np.issubdtype(floats.dtype, np.floating)

True

In [7]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [8]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
arr.reshape((4,2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [14]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [27]:
arr1 = np.array([[1, 2 , 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
arr = np.random.randn(5, 2)
arr

array([[-1.00331607, -1.89408415],
       [-0.43785188,  0.41778929],
       [-1.85893545, -1.38910769],
       [ 0.86734429, -0.13488606],
       [ 0.8116766 ,  1.15628644]])

In [33]:
first, second, third = np.split(arr, [1, 3])

In [34]:
first

array([[-1.00331607, -1.89408415]])

In [35]:
second

array([[-0.43785188,  0.41778929],
       [-1.85893545, -1.38910769]])

In [36]:
third

array([[ 0.86734429, -0.13488606],
       [ 0.8116766 ,  1.15628644]])

In [37]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.31481469, -1.01520603],
       [-0.26318237,  0.16932882],
       [ 0.54391982,  0.87361675]])

In [38]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-1.31481469, -1.01520603,  3.        ],
       [-0.26318237,  0.16932882,  4.        ],
       [ 0.54391982,  0.87361675,  5.        ]])

In [39]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [40]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [41]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [42]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [43]:
arr = np.random.randn(2, 2)
arr

array([[ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277]])

In [44]:
arr.repeat(2, axis=0)

array([[ 2.13142217,  1.18099982],
       [ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277],
       [-0.69759932, -0.25642277]])

In [45]:
arr.repeat([2, 3], axis=0)

array([[ 2.13142217,  1.18099982],
       [ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277],
       [-0.69759932, -0.25642277],
       [-0.69759932, -0.25642277]])

In [46]:
arr.repeat([2, 3], axis=1)

array([[ 2.13142217,  2.13142217,  1.18099982,  1.18099982,  1.18099982],
       [-0.69759932, -0.69759932, -0.25642277, -0.25642277, -0.25642277]])

In [47]:
arr

array([[ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277]])

In [49]:
np.tile(arr, 2)

array([[ 2.13142217,  1.18099982,  2.13142217,  1.18099982],
       [-0.69759932, -0.25642277, -0.69759932, -0.25642277]])

In [50]:
np.tile(arr, (2, 1))

array([[ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277],
       [ 2.13142217,  1.18099982],
       [-0.69759932, -0.25642277]])

In [51]:
np.tile(arr, (3, 2))

array([[ 2.13142217,  1.18099982,  2.13142217,  1.18099982],
       [-0.69759932, -0.25642277, -0.69759932, -0.25642277],
       [ 2.13142217,  1.18099982,  2.13142217,  1.18099982],
       [-0.69759932, -0.25642277, -0.69759932, -0.25642277],
       [ 2.13142217,  1.18099982,  2.13142217,  1.18099982],
       [-0.69759932, -0.25642277, -0.69759932, -0.25642277]])

In [69]:
tile = np.array([
    ['/','\\'],
    ['\\','/']])
for linha in np.tile(tile, (3,10)):
    for elemento in linha:
        print(elemento,end='')
    print()

/\/\/\/\/\/\/\/\/\/\
\/\/\/\/\/\/\/\/\/\/
/\/\/\/\/\/\/\/\/\/\
\/\/\/\/\/\/\/\/\/\/
/\/\/\/\/\/\/\/\/\/\
\/\/\/\/\/\/\/\/\/\/


In [70]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [71]:
arr.take(inds)

array([700, 100, 200, 600])

In [72]:
arr.put(inds, 42)

In [73]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [74]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[ 1.3991127 , -0.0264441 ,  0.45812067,  1.24531142],
       [-1.26185294,  0.68450066,  0.47010325,  0.54703171]])

In [75]:
arr.take(inds, axis=1)

array([[ 0.45812067,  1.3991127 ,  0.45812067, -0.0264441 ],
       [ 0.47010325, -1.26185294,  0.47010325,  0.68450066]])

In [76]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [78]:
arr.sum()

45

In [79]:
np.random.seed(123456)
arr = np.random.randn(5,5)
arr[::2].sort(1)
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [81]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [83]:
(arr[:, :-1] < arr[:, 1:]).all(1)

array([ True, False,  True, False,  True])

In [84]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [85]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [86]:
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [87]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [88]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [89]:
list(zip(last_name[sorter], first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]