In [1]:
import numpy as np

In [3]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x[1]

array([[4],
       [5],
       [6]])

In [38]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
x[:,:]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])